spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/issues?serverTimezone=UTC
    username: root
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: yavuz
      password : spring

server:
  port: 8080
